class JournalEntry:
    def __init__(self, entry_id, user_id, date, content, reflection=None):
        self.entry_id = entry_id
        self.user_id = user_id
        self.date = date
        self.content = content
        self.reflection = reflection  # generated by RAG